### ISSUE TITLE
Bash vs PowerShell

### ISSUE THREAD

**Issue by Williams-Nest** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#102] opened 2019-09-25 12:06 UTC
There is something fundamentally wrong with the Shell filosofi of these Azure courses.

It is not ours or your (Microsoft) duty to tell people what shell language they should use. If there are two possible ways to do things - one in Bash - and one in PowerShell - then both versions should be available in all labs.

It does NOT make sense to only give the Bash instructions to a happy PowerShell superuser and vice versa.

This is the only question I get from my students that I cannot give a logical answer on. 
And I get this question a lot!

**Comment by polichtm** [comment] 2019-09-25 18:21
That's an interesting suggestion, however:
1) there is no full parity between Azure CLI and Azure PowerShell
2) students are expected to know both for the exam
rgds
Marcin

**Comment by polichtm** [comment] 2019-09-25 18:21
duplicate of #2

**Closed by polichtm** 2019-09-25 18:21 UTC
